db.restaurantData.find().pretty()
db.restaurantData.find({}, { restaurant_id : 1, name: 1, borough: 1, cuisine: 1}).pretty()
db.restaurantData.find({}, { restaurant_id : 1, name: 1, borough: 1, cuisine: 1, _id: 0 }).pretty()
db.restaurantData.find({}, { restaurant_id : 1, name: 1, borough: 1, address: { zipcode : 1}, _id : 0 }).pretty()
db.restaurantData.find({borough : "Bronx"}).pretty()
db.restaurantData.find({borough : "Bronx"}, {name : 1}).limit(5).pretty()
db.restaurantData.find({borough : "Bronx"}, {name : 1}).skip(5).limit(5).pretty()
db.restaurantData.find( {"grades.score": {$gt: 90} }).pretty()
db.restaurantData.find({ "grades.score": {$lt: 100, $gt: 80}}, {"grades.score": 1}).pretty()
db.restaurantData.find({"address.coord": {$lt: -95.754168}}, {address: 1, _id: 0}).pretty()
db.restaurantData.find( { $and: [ {cuisine: {$ne: "American " }} , {"grades.score": {$gt: 70}} , {"address.coord": {$lt: -65.754168}} ]} ).pretty()
db.restaurantData.find( { $and: [{cuisine: {$ne: "American " }}, { "grades.grade" : "A"}, { borough: {$ne: "Brooklyn"} } ]} ).sort( { cuisine : -1} ).pretty()
db.restaurantData.find({ name : { $regex: /^Wil/ } }, { restaurant_id : 1 , name : 1, borough : 1, cuisine : 1, _id: 0}).pretty()
db.restaurantData.find({ name : { $regex: /ces$/ } }, { restaurant_id : 1 , name : 1, borough : 1, cuisine : 1, _id: 0}).pretty()
db.restaurantData.find({ name : { $regex: /Reg/ } }, { restaurant_id : 1 , name : 1, borough : 1, cuisine : 1, _id: 0}).pretty()
db.restaurantData.find( { $and: [ {borough : "Bronx"}, { cuisine: { $in: [ "American ", "Chinese" ] }}]} ).pretty()
db.restaurantData.find( { borough: { $in: ["Staten Island", "Queens", "Bronx", "Brooklyn"]}}).pretty()
